import { Metadata } from "next";
import React, { FC, PropsWithChildren, Suspense } from "react";
import MUIThemeProvider from "@src/providers/MUIThemeProvider";
import PhotoboothProvider from "@src/contexts/PhotoboothProvider";
import TanstackQueryProvider from "@src/providers/TanstackQueryProvider";
import NotistackProvider from "@src/providers/NotistackProvider";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <MUIThemeProvider>
      <TanstackQueryProvider>
        <Suspense>
          <PhotoboothProvider>
            <html lang="en">
              <body>
                <NotistackProvider>{children}</NotistackProvider>
              </body>
            </html>
          </PhotoboothProvider>
        </Suspense>
      </TanstackQueryProvider>
    </MUIThemeProvider>
  );
};

export default RootLayout;
